baseurl = "https://blog.snk.ws"
title = "Michael McAllister"
languagecode = "en"
defaultcontentlanguage = "en"
theme="anatole"
paginate = 10
disqusShortname = "blog-skunkw0rks-io"
googleAnalytics = "UA-88367397-1"
enableRobotsTXT = true
favicon = "favicons/"

pygmentsCodeFences = true
pygmentsUseClasses = true

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "Resume"
weight = 300
identifier = "Resume"
url = "https://github.com/michaelmcallister/CV/releases/latest/download/resume.pdf"

[[menu.main]]
name = "Code"
weight = 300
identifier = "Code"
url = "/code/"

[params]
title = "Michael McAllister"
author = "Michael McAllister"
profilePicture = "images/profile.png"
displayMode = "dark"
doNotLoadAnimations = true
customCss = ["css/syntax.css"]


## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/mpmcallister"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/michaelmcallister/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:me@michaelmcallister.org"

[[params.socialIcons]]
  name = "RSS"
  icon = "fas fa-rss"
  weight = 2
  url = "index.xml"
