baseurl = "https://blog.skunkw0rks.io"
title = "Blog"
languageCode = "en-us"
MetaDataFormat = "toml"
theme="hyde-x"
paginate = 10

[author]
    name = "Michael McAllister"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"

[params]
    tagline = "I hear this \"cloud\" thing is really taking off..."
    github = "https://github.com/michaelmcallister"
    linkedin = "https://www.linkedin.com/in/mpmcallister"
