baseurl = "https://blog.skunkw0rks.io"
title = "Blog"
languageCode = "en-us"
MetaDataFormat = "toml"
theme="hyde-x"
paginate = 10
disqusShortname = "blog-skunkw0rks-io"

[author]
    name = "Michael McAllister"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"

[[menu.main]]
    name = "Resume"
    url = "https://resume.skunkw0rks.io"

[params]
    gravatarHash = "dadad03da8b24f24d6c12549f4e53e9d"
    highlight = "nord"
    tagline = "I hear this \"cloud\" thing is really taking off..."
    github = "https://github.com/michaelmcallister"
    linkedin = "https://www.linkedin.com/in/mpmcallister"
    keybase = "https://keybase.io/mmcallister"
    rss = true
    googleAnalytics = "UA-88367397-1"
