baseurl = "https://blog.skunkw0rks.io"
title = "Blog"
languageCode = "en-us"
MetaDataFormat = "toml"
theme="hyde-x"
paginate = 10
disqusShortname = "blog-skunkw0rks-io"

[author]
    name = "Michael McAllister"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"

[params]
    gravatarHash = "5a31e3853ec7302a67f5c6342b8915d2"
    highlight = "sunburst"
    tagline = "I hear this \"cloud\" thing is really taking off..."
    github = "https://github.com/michaelmcallister"
    linkedin = "https://www.linkedin.com/in/mpmcallister"
    rss = true
